[package]
name = "rser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
ansi_term = "0.12.1"
sdl2 = "0.35.2"
bit = "0.1.1"

[profile.release]
opt-level = 3
